### ISSUE TITLE
[Form]: Read order in forms is not correct and column layout does not work for groups.

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents-react#5704]
### Describe the bug

Hi team, 

A couple issues:
1. It was brought to my attention that the read order of the forms is not correct. According to our designers, the read order should be top to bottom then followed by left to right. However, with the current implementation and the read order is left to right, then top to bottom. 
2. When you have two groups and define multiple columns span for your breakpoints, the groups will not break into multiple columns.

Please refer to: https://experience.sap.com/fiori-design-web/form/#top

### Isolated Example

Issue 1: https://stackblitz.com/edit/github-pzlhay?file=src%2FApp.tsx
Issue 2: https://stackblitz.com/edit/github-rmcazv?file=src%2FApp.tsx

### Reproduction steps

1. Please see the isolated example, as well as the sapui5 demo links in the 'Expected Behavior' field below.

### Expected Behaviour

For issue 1, here is an example of the expected behavior from ui5 classic framework. SimpleForm. https://ui5.sap.com/#/entity/sap.ui.layout.form.SimpleForm/sample/sap.ui.layout.sample.SimpleForm_Column_oneGroup234

For issue 2, here is an example of the expected behavior from ui5 classic framework. SimpleForm.
https://ui5.sap.com/#/entity/sap.ui.layout.form.SimpleForm/sample/sap.ui.layout.sample.SimpleForm_Column_twoGroups234

### Screenshots or Videos

Issue 1:
<img width="815" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/38701667/ea5ea126-7850-41fd-aebd-afbf46161836">
<img width="841" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/38701667/6e4f4fb8-3e7f-4485-a667-fc42471f5071">
Issue 2:
<img width="1543" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/38701667/2422dd77-7c9f-45cf-936d-150b26aa68d6">

<img width="1543" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/38701667/ea0b5a47-2388-4e85-ad0c-929e26f7bf23">

### UI5 Web Components for React Version

main

### UI5 Web Components Version

main

### Browser

Chrome, Edge, Firefox, Safari

### Organization

SF

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Hi @allen138,
Issue 1 should be fixed in [v1.27.1](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v1.27.1).

**Comment by i832513** [comment]
@MarcusNotheis ,
We noticed that the latest code for Forms works fine when there are zero groups. But whenever we add 1 group the read ordering is not fixed unexpectedly. You may have been aware of that already - but I wanted to bring it up in case there is something else we can do to fix the Tab Order/Read Order of large forms to go top-down first as per the guidelines.

**Comment by MarcusNotheis** [comment]
#5824 should fix the column layout if only FormGroups are used.
As discussed via Slack, providing a fix for mixed children `FormItems` and `FormGroups` is not feasible with our current Form implementation, so I would like to ask you to only use `FormItems` or `FormGroups` as children of the `Form`, but not mixing them.
