### ISSUE TITLE
Unable to Customize Donut Chart Hover Label Formatter

### ISSUE THREAD

**Issue by eeshamoona** [SAP/ui5-webcomponents-react#613]
Trying to reproduce this example where the `formatter` changes the labels in the legend AND in the on hover label on the donut chart. When trying to reproduce the `formatter` only changes the labels in the legend. 

Using the latest version of ui5 web-components react charts: 0.9.9

https://sap.github.io/ui5-webcomponents-react/?path=/docs/charts-donutchart--with-formatter#with-formatter
<img width="355" alt="Screen Shot 2020-07-20 at 10 36 41 AM" src="https://user-images.githubusercontent.com/29615978/87977456-9f475480-ca83-11ea-840e-ed45862bccd1.png">

**Comment by Lukas742** [comment]
Hi @eeshamoona 

Could you try updating `@ui5/webcomponents-react-charts` to our latest rc (`0.10.0-rc.7`), this should solve the issue.

**Comment by eeshamoona** [comment]
Updated version to `0.10.0-rc.7` and the issue still persists.

**Comment by Lukas742** [comment]
I opened a PR that should fix the issue. The formatter was only applied to the Tooltip if the dimension accessor was `name`. That's why it was hard for me to detect this issue in the beginning because we are using `name`  as accessor in our demo.

We will let you know when this is released.

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react-charts@0.10.0-rc.10`
